// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAukol9D9xcFKjZo_Lx7UDcoP37or_xqkA',
    appId: '1:76591559083:web:1048515229e23919fbe2ee',
    messagingSenderId: '76591559083',
    projectId: 'mobilfinal-eab94',
    authDomain: 'mobilfinal-eab94.firebaseapp.com',
    storageBucket: 'mobilfinal-eab94.firebasestorage.app',
    measurementId: 'G-4B9N577P4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsi_IzwVOipc_9vrHS6q485Fe3r9-_eHA',
    appId: '1:76591559083:android:da5214d5c315d236fbe2ee',
    messagingSenderId: '76591559083',
    projectId: 'mobilfinal-eab94',
    storageBucket: 'mobilfinal-eab94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO3zYyQl09SttPI_Rwt1_8TMHit_0NGu0',
    appId: '1:76591559083:ios:7f97abcbba20236dfbe2ee',
    messagingSenderId: '76591559083',
    projectId: 'mobilfinal-eab94',
    storageBucket: 'mobilfinal-eab94.firebasestorage.app',
    iosBundleId: 'com.example.odev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO3zYyQl09SttPI_Rwt1_8TMHit_0NGu0',
    appId: '1:76591559083:ios:7f97abcbba20236dfbe2ee',
    messagingSenderId: '76591559083',
    projectId: 'mobilfinal-eab94',
    storageBucket: 'mobilfinal-eab94.firebasestorage.app',
    iosBundleId: 'com.example.odev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAukol9D9xcFKjZo_Lx7UDcoP37or_xqkA',
    appId: '1:76591559083:web:9ecd739600d5d43dfbe2ee',
    messagingSenderId: '76591559083',
    projectId: 'mobilfinal-eab94',
    authDomain: 'mobilfinal-eab94.firebaseapp.com',
    storageBucket: 'mobilfinal-eab94.firebasestorage.app',
    measurementId: 'G-QD0LZZCYEK',
  );
}
